# Generated by Django 4.0.6 on 2022-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='missions',
            field=models.ManyToManyField(related_name='characters', to='missions.missions'),
        ),
    ]
