# Generated by Django 4.0.6 on 2022-07-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='username',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='character',
            name='password',
        ),
    ]
