# Generated by Django 4.0.6 on 2022-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_initial'),
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='missions',
            field=models.ManyToManyField(related_name='characters', to='missions.missions'),
        ),
    ]
