# Generated by Django 4.0.6 on 2022-07-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_charactersmissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharactersMissions',
        ),
    ]
