# Generated by Django 4.0.6 on 2022-07-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "intellect_modifier",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                (
                    "strength_modifier",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                (
                    "agility_modifier",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
            ],
        ),
    ]
