# Generated by Django 4.0.6 on 2022-07-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_game_master",
            field=models.BooleanField(default=False),
        ),
    ]
