# Generated by Django 4.0.6 on 2022-07-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="level_requires",
            new_name="level_required",
        ),
    ]
