# Generated by Django 4.0.6 on 2022-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artisans", "0001_initial"),
        ("items", "0002_rename_level_requires_item_level_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="artisan",
            field=models.ForeignKey(
                on_delete=models.SET("Wanted"),
                related_name="items",
                to="artisans.artisan",
            ),
        ),
    ]
