# Generated by Django 4.0.6 on 2022-07-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missions',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
