# Generated by Django 4.0.6 on 2022-07-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missions',
            name='xp',
        ),
    ]
