# Generated by Django 4.0.6 on 2022-07-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_missions_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missions',
            name='completed',
        ),
    ]
